FileVersion = 1

[Project]
Name = "nativefiledialog-beef"
TargetType = "BeefLib"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\nativefiledialogDebug.lib"]
OtherLinkFlags = "$(LinkFlags) comctl32.lib"

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\nativefiledialogRelease.lib"]
OtherLinkFlags = "$(LinkFlags) comctl32.lib"

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\nativefiledialogRelease.lib"]
OtherLinkFlags = "$(LinkFlags) comctl32.lib"

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\nativefiledialogRelease.lib"]
OtherLinkFlags = "$(LinkFlags) comctl32.lib"

[Configs.Debug.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libnativefiledialogDebug.a"]
OtherLinkFlags = "$(LinkFlags) -framework AppKit"

[Configs.Release.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libnativefiledialogRelease.a"]
OtherLinkFlags = "$(LinkFlags) -framework AppKit"

[Configs.Paranoid.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libnativefiledialogRelease.a"]
OtherLinkFlags = "$(LinkFlags) -framework AppKit"

[Configs.Test.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libnativefiledialogRelease.a"]
OtherLinkFlags = "$(LinkFlags) -framework AppKit"
